# packages.yaml -> all:require: "%gcc@9.4.0"
# comment this out if you want to use a different compiler
compilers:
- compiler:
    spec: gcc@9.4.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu20.04
    # apt installed on all nodes regardless of target arch
    #target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []

# cannot build for aarch64,ppc64le
- compiler:
    spec: oneapi@2021.4.0
    paths:
      cc: /modules/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/intel-oneapi-compilers-2021.4.0-zf2notg6hjsb2aa3py7ewc5eivqrkeq7/compiler/latest/linux/bin/icx
      cxx: /modules/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/intel-oneapi-compilers-2021.4.0-zf2notg6hjsb2aa3py7ewc5eivqrkeq7/compiler/latest/linux/bin/icpx
      f77: /modules/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/intel-oneapi-compilers-2021.4.0-zf2notg6hjsb2aa3py7ewc5eivqrkeq7/compiler/latest/linux/bin/ifx
      fc: /modules/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/intel-oneapi-compilers-2021.4.0-zf2notg6hjsb2aa3py7ewc5eivqrkeq7/compiler/latest/linux/bin/ifx
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []


# compiles everything optimized for a pentium 4
# cannot build for aarch64,ppc64le
- compiler:
    spec: intel@2021.4.0
    paths:
      cc: /modules/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/intel-oneapi-compilers-classic-2021.4.0-7u6ilzpqn5lj4sgrcdwnemmilrr3kemc/compiler/latest/linux/bin/intel64/icc
      cxx: /modules/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/intel-oneapi-compilers-classic-2021.4.0-7u6ilzpqn5lj4sgrcdwnemmilrr3kemc/compiler/latest/linux/bin/intel64/icpc
      f77: /modules/spack-0.18.1/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/intel-oneapi-compilers-classic-2021.4.0-7u6ilzpqn5lj4sgrcdwnemmilrr3kemc/compiler/latest/linux/bin/intel64/ifort
      fc: /modules/spack-0.18.1/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/intel-oneapi-compilers-classic-2021.4.0-7u6ilzpqn5lj4sgrcdwnemmilrr3kemc/compiler/latest/linux/bin/intel64/ifort
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
