packages:
  all:
    # TODO make sure package-maintainer loses write privileges to installs
    permissions:
      read: world
      write: user
      group: package-maintainer
    variants:
    #- cuda_arch=52,61,70,75,80,86 # the ones we have in unity as of 8/2022
    - cuda_arch=52,53,60,61,62,70,72,75,80,86 # all existing arches >= 52 as of 8/2022
    #- fabrics=ucx
    # Can't be set here because of conflict between what ucx and openfabrics provide
    # - fabrics=verbs,psm3,rxm,rxd,tcp,shm

    # spack likes to ignore preferences, so we make them non negotiable
    # comment these out if you want to do something different
    require: '%gcc@9.4.0'
  mpi:
    require: openmpi
  blas:
    require: openblas

  # BUGFIXES
  ############################################################################################
  # raises error, cannot set suid with group writable
  openssh:
    permissions:
      write: user
    externals:
    - spec: openssh@8.2p1
      prefix: /usr
  kokkos:
    variants:
    - cuda_arch=52

  # DEFAULT VARIANTS
  ############################################################################################
  openmpi:
    buildable: false # please be careful making new ones
    variants:
    # default mpi would like our slurm to have pmix but it doesn't, it'll have to make do with pmi
    - +pmi
    - +internal-pmix
    - +cuda
    - fabrics=ucx
    - schedulers=slurm
    #- "+legacylaunchers"

  libfabric:
    variants:
    - fabrics=verbs,psm3,rxm,rxd,tcp,shm

  ucx:
    variants:
    - +cm
    - +verbs
    - +rc
    - +ud
    - +dc
    - +cma
    - +dm
    - +knem
    - +cuda
    - +gdrcopy

  opencv:
    variants:
    - +annotation
    - +avfoundation
    - +barcode
    - +bgsegm
    - +bioinspired
    - +calib3d
    - +cap_ios
    - +carotene
    - +ccalib
    - +clp
    - +cpufeatures
    - +createsamples
    - +cublas
    - +cuda
    - +cudaarithm
    - +cudabgsegm
    - +cudacodec
    - +cudafeatures2d
    - +cudafilters
    - +cudaimgproc
    - +cudalegacy
    - +cudaobjdetect
    - +cudaoptflow
    - +cudastereo
    - +cudawarping
    - +cudev
    - +cudnn
    - +cufft
    - +cvv
    - +datasets
    - +directx
    - +dnn
    - +dnn_objdetect
    - +dnn_superres
    - +dpm
    - +dshow
    - +eigen
    - +face
    - +fast-math
    - +features2d
    - +ffmpeg
    - +flann
    - +freetype
    - +fuzzy
    - +hdf
    - +hfs
    - +highgui
    - +hpx
    - +img_hash
    - +imgcodec_hdr
    - +imgcodec_pfm
    - +imgcodec_pxm
    - +imgcodec_sunraster
    - +imgcodecs
    - +imgproc
    - +intensity_transform
    - +interactive-calibration
    - +ipo
    - +itt
    - +jasper
    - +jpeg
    - +lapack
    - +line_descriptor
    - +mcc
    - +ml
    - +model-diagnostics
    - +msmf
    - +msmf_dxva
    - +objdetect
    - +onnx
    - +opencl
    - +openexr
    - +opengl
    - +openjpeg
    - +openmp
    - +optflow
    - +phase_unwrapping
    - +photo
    - +plaidml
    - +plot
    - +png
    - +protobuf
    - +pthreads_pf
    - +python3
    - +quality
    - +quirc
    - +rapid
    - +reg
    - +rgbd
    - +saliency
    - +stereo
    - +stitching
    - +structured_light
    - +superres
    - +surface_matching
    - +tbb
    - +tengine
    - +tesseract
    - +text
    - +tiff
    - +tracking
    - +traincascade
    - +ts
    - +v4l
    - +version
    - +video
    - +videoio
    - +videostab
    - +visualisation
    - +viz
    - +vtk
    - +vulcan
    - +webp
    - +wechat_qrcode
    - +win32ui
    - +xfeatures2d
    - +ximgproc
    - +xobjdetect
    - +xphoto

  lammps:
    # noemclature may have changed regarding user- prefix in some versions
    variants:
    - +asphere
    - +body
    - +class2
    - +colloid
    - +compress
    - +coreshell~cuda~cuda_mps
    - +dipole
    - +granular
    - +kokkos
    - +kspace
    - +manybody
    - +mc
    - +misc
    - +molecule
    - +mpiio
    - +peri
    - +python
    - +qeq
    - +replica
    - +rigid
    - +shock
    - +snap
    - +spin
    - +srd
    - +voronoi
    - +user-atc
    - +user-bocs
    - +user-cgdna
    - +user-cgsdk
    - +user-colvars
    - +user-diffraction
    - +user-dpd
    - +user-drude
    - +user-eff
    - +user-fep
    - +user-h5md
    - +user-lb
    - +user-manifold
    - +user-meamc
    - +user-meso
    - +user-mgpt
    - +user-misc
    - +user-mofff
    - +user-molfile
    - +user-netcdf
    - +user-phonon
    - +user-plumed
    - +user-ptm
    - +user-qtb
    - +user-reaxc
    - +user-reaxff
    - +user-scafacos
    - +user-smd
    - +user-smtbq
    - +user-sph
    - +user-tally
    - +user-uef
    - +user-yaff

  charmpp:
    variants: +cuda backend=multicore

  namd:
    variants:
    - +cuda
    - backend=ucx

  # EXTERNALS
  ############################################################################################
  # the texlive spack install was broken at the time
  texlive:
    buildable: false
    externals:
    - spec: texlive@20220000
      modules:
      - texlive/2022

  apptainer:
    buildable: false
    externals:
    - spec: apptainer@1.3.1
      modules:
      - apptainer/latest

  # it's important that we all use the same slurm
  # when Unity slurm is updated this version number should also be updated
  slurm:
    buildable: false
    externals:
    - spec: slurm@20.02.7 target=x86_64
      prefix: /usr
    - spec: slurm@20.02.7 target=ppc64le
      prefix: /usr/lib/powerpc64le-linux-gnu/
    - spec: slurm@20.02.7 target=aarch64
      prefix: /usr/lib/aarch64-linux-gnu/

  pmix:
    buildable: false
    externals:
    - spec: pmix@3.1.5-1 target=x86_64
      prefix: /usr/lib/x86_64-linux-gnu/pmix/
    - spec: pmix@3.1.5-1 target=ppc64le
      prefix: /usr/lib/powerpc64le-linux-gnu/pmix/
    - spec: pmix@3.1.5-1 target=aarch64
      prefix: /usr/lib/aarch64-linux-gnu/pmix/

  libevent:
    externals:
    # I don't want buildable: false because there are other libevents in use
    # spack can't make 2.1.7 on it's own so the only option is the external
    - spec: libevent@2.1.7 target=x86_64
      prefix: /usr/lib/x86_64-linux-gnu/
    - spec: libevent@2.1.7 target=ppc64le
      prefix: /usr/lib/powerpc64le-linux-gnu/
    - spec: libevent@2.1.7 target=aarch64
      prefix: /usr/lib/aarch64-linux-gnu/

  # For IB nodes; recommended by https://mvapich.cse.ohio-state.edu/userguide/userguide_spack/
  rdma-core:
    buildable: false
    externals:
    - spec: rdma-core@28.0
      prefix: /usr

  # `spack external find --all`
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.16.1
      prefix: /usr
  bash:
    externals:
    - spec: bash@5.0.17
      prefix: /usr
  binutils:
    externals:
    - spec: binutils@2.34
      prefix: /usr
  bison:
    externals:
    - spec: bison@3.5.1
      prefix: /usr
  bzip2:
    externals:
    - spec: bzip2@1.0.8
      prefix: /usr
  cmake:
    externals:
    - spec: cmake@3.16.3
      prefix: /usr
  coreutils:
    externals:
    - spec: coreutils@8.30
      prefix: /usr
  cpio:
    externals:
    - spec: cpio@2.13
      prefix: /usr
  curl:
    externals:
    - spec: curl@7.68.0+gssapi+ldap+nghttp2
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.7
      prefix: /usr
  dos2unix:
    externals:
    - spec: dos2unix@7.4.0
      prefix: /usr
  doxygen:
    externals:
    - spec: doxygen@1.8.17~graphviz~mscgen
      prefix: /usr
  file:
    externals:
    - spec: file@5.38
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.7.0
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@5.0.1
      prefix: /usr
  gcc:
    externals:
    - spec: gcc@9.4.0 languages=c,c++,fortran
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/x86_64-linux-gnu-gcc-9
          cxx: /usr/bin/x86_64-linux-gnu-g++-9
          fortran: /usr/bin/x86_64-linux-gnu-gfortran-9
    - spec: gcc@9.4.0
      prefix: /usr
  gdal:
    externals:
    - spec: gdal@3.0.4
      prefix: /usr
  gettext:
    externals:
    - spec: gettext@0.19.8.1
      prefix: /usr
  ghostscript:
    externals:
    - spec: ghostscript@9.50
      prefix: /usr
  git:
    externals:
    - spec: git@2.25.1~tcltk
      prefix: /usr
  git-lfs:
    externals:
    - spec: git-lfs@2.9.2
      prefix: /usr
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.4
      prefix: /usr
  hdf5:
    externals:
    - spec: hdf5@1.10.4+cxx+fortran+hl+java~mpi+szip+threadsafe~tools api=v18
      prefix: /usr
  openjdk:
    externals:
    - spec: openjdk@11.0.20.1_1-post-Ubuntu-0ubuntu120.04
      prefix: /usr
  libfuse:
    externals:
    - spec: libfuse@2.9.9
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
  llvm:
    externals:
    - spec: llvm@10.0.0+clang~lld~lldb
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/clang
          cxx: /usr/bin/clang++-10
  llvm-doe:
    externals:
    - spec: llvm-doe@10.0.0+clang~lld~lldb
      prefix: /usr
      extra_attributes:
        compilers:
          c: /usr/bin/clang
          cxx: /usr/bin/clang++-10
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
